# Generated by Django 2.0.5 on 2019-02-04 12:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_card_code', message='Unpropriate card code. Must be numeric.', regex='^[0-9]+$')])),
                ('status', models.CharField(choices=[('free', 'Free'), ('taken', 'Taken')], default='free', max_length=10)),
                ('level_of_privilege', models.CharField(choices=[('employee', 'Employee'), ('guest', 'Guest'), ('master', 'Master'), ('stuff', 'Stuff')], default='guest', max_length=10)),
            ],
            options={
                'ordering': ('level_of_privilege', 'name', 'status'),
            },
            managers=[
                ('taken', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeCardUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(null=True)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.Card')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards_employee_card_usage', to='company.Employee')),
            ],
            options={
                'ordering': ('employee', '-start_time', '-end_time', 'description'),
            },
        ),
        migrations.CreateModel(
            name='VisitorCardUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(null=True)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.Card')),
                ('visitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards_visitor_card_usage', to='company.Visitor')),
            ],
            options={
                'ordering': ('visitor', '-start_time', '-end_time', 'description'),
            },
        ),
    ]
