# Generated by Django 2.0.5 on 2018-11-04 21:05

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('code', models.BigIntegerField(db_index=True, unique=True)),
                ('status', models.CharField(choices=[('free', 'Free'), ('taken', 'Taken')], default='free', max_length=10)),
                ('level_of_privilege', models.CharField(choices=[('employee', 'Employee'), ('guest', 'Guest'), ('master', 'Master'), ('stuff', 'Stuff')], default='guest', max_length=10)),
            ],
            options={
                'ordering': ('level_of_privilege', 'name', 'status'),
            },
            managers=[
                ('free', django.db.models.manager.Manager()),
            ],
        ),
    ]
