# Generated by Django 2.0.5 on 2019-02-04 16:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={},
        ),
        migrations.AlterModelManagers(
            name='card',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='code',
            field=models.CharField(db_index=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_card_code', message='Niepoprawny format karty.                                                         Kod karty może składać się tylko z cyfr 0-9.', regex='^[0-9]+$')]),
        ),
    ]
