# Generated by Django 2.0.5 on 2018-11-04 21:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_employeecardusage_visitorcardusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='code',
            field=models.CharField(db_index=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_card_code', message='Unpropriate card code. Must be numeric.', regex='^[0-9]+$')]),
        ),
    ]
