# Generated by Django 2.0.5 on 2019-02-04 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20190204_1701'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='card',
            managers=[
            ],
        ),
    ]
