# Generated by Django 2.0.5 on 2018-11-05 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_auto_20181104_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeecardusage',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='visitorcardusage',
            name='visitor',
        ),
        migrations.DeleteModel(
            name='EmployeeCardUsage',
        ),
        migrations.DeleteModel(
            name='VisitorCardUsage',
        ),
    ]
