# Generated by Django 2.0.5 on 2018-11-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_meeting_room_roomreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='kind',
            field=models.CharField(choices=[('in', 'Internal'), ('ext', 'External'), ('con', 'Conference')], default='in', max_length=5),
        ),
    ]
