# Generated by Django 2.0.5 on 2019-02-05 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20190205_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingparticipant',
            name='meeting',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_meeting_participant_participant', to='company.Meeting'),
        ),
    ]
