# Generated by Django 2.0.5 on 2018-11-17 09:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_meeting_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingParticipants',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('meeting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_meeting_participant_participant', to='company.Meeting')),
                ('visitor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_meeting_participant_visitor', to='company.Visitor')),
            ],
        ),
    ]
