# Generated by Django 2.0.5 on 2018-11-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_meetingparticipants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingparticipants',
            name='visitor',
        ),
        migrations.AddField(
            model_name='meetingparticipants',
            name='employees',
            field=models.ManyToManyField(related_name='employees_meeting_participants', to='company.Employee'),
        ),
        migrations.AddField(
            model_name='meetingparticipants',
            name='visitors',
            field=models.ManyToManyField(related_name='visitors_meeting_participants', to='company.Visitor'),
        ),
    ]
