# Generated by Django 2.0.5 on 2019-02-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20190206_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomreservation',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
