# Generated by Django 2.0.5 on 2018-11-17 15:46

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False


    dependencies = [
        ('company', '0005_auto_20181117_1522'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeetingParticipants',
            new_name='MeetingParticipant',
        ),
    ]
