# Generated by Django 2.0.5 on 2019-02-04 16:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import document.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('kind_of_document', models.CharField(choices=[('pdf', 'PDF'), ('wrd', 'Word'), ('xls', 'Excel'), ('pst', 'Presentation'), ('oth', 'Other')], default='pdf', max_length=3)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(null=True)),
                ('status', models.CharField(choices=[('s', 'Sent'), ('p', 'Pending'), ('e', 'Error'), ('l', 'Loaded')], default='l', max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('extension', models.CharField(blank=True, db_index=True, max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_file_extension', message='Inappropriate file extension. Must be numeric.', regex='^(\\S{1,10})$')])),
                ('file', models.FileField(upload_to=document.models.UploadToPathAndRename('EmployeeDocuments/'))),
            ],
            options={
                'ordering': ('name', 'extension'),
            },
        ),
        migrations.CreateModel(
            name='MeetingDocument',
            fields=[
                ('kind_of_document', models.CharField(choices=[('pdf', 'PDF'), ('wrd', 'Word'), ('xls', 'Excel'), ('pst', 'Presentation'), ('oth', 'Other')], default='pdf', max_length=3)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(null=True)),
                ('status', models.CharField(choices=[('s', 'Sent'), ('p', 'Pending'), ('e', 'Error'), ('l', 'Loaded')], default='l', max_length=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('extension', models.CharField(blank=True, db_index=True, max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_file_extension', message='Inappropriate file extension. Must be numeric.', regex='^(\\S{1,10})$')])),
                ('file', models.FileField(upload_to=document.models.UploadToPathAndRename('MeetingDocuments/'))),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_documents', to='company.Meeting')),
            ],
            options={
                'ordering': ('name', 'extension'),
            },
        ),
    ]
