# Generated by Django 2.0.5 on 2019-02-04 12:08

from django.db import migrations, models
import document.models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='file',
            field=models.FileField(upload_to=document.models.UploadToPathAndRename('EmployeeDocuments/')),
        ),
        migrations.AlterField(
            model_name='meetingdocument',
            name='file',
            field=models.FileField(upload_to=document.models.UploadToPathAndRename('MeetingDocuments/')),
        ),
    ]
