# Generated by Django 2.0.5 on 2018-12-06 06:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20181202_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingdocument',
            name='extension',
            field=models.CharField(blank=True, db_index=True, max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_file_extension', message='Inappropriate file extension. Must be numeric.', regex='^(\\S{1,10})$')]),
        ),
        migrations.AlterField(
            model_name='meetingdocument',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
