# Generated by Django 2.0.5 on 2018-12-06 06:34

from django.db import migrations, models
import document.models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_auto_20181206_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingdocument',
            name='file',
            field=models.FileField(upload_to=document.models.UploadToPathAndRename('upload/here')),
        ),
    ]
